# Generated by Django 4.1.5 on 2023-02-04 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_contenttopost_profile_verified_alter_post_thumbnail_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contenttopost',
            old_name='context_type',
            new_name='content_type',
        ),
        migrations.AddField(
            model_name='contenttopost',
            name='editor_type',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='contenttopost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/post/image'),
        ),
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.TextField(blank=True, help_text='Add tags comma separated without space', null=True),
        ),
        migrations.AlterField(
            model_name='contenttopost',
            name='content',
            field=models.TextField(blank=True, help_text='If image has been chosen, this field will work as image description', null=True),
        ),
        migrations.AlterField(
            model_name='contenttopost',
            name='priority',
            field=models.IntegerField(default=1, help_text='Here priority in ascending order like 1 will appear on top'),
        ),
    ]
