# Generated by Django 4.1.5 on 2023-02-04 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_context_type_contenttopost_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='media/category/thumbnail'),
        ),
        migrations.AlterField(
            model_name='contenttopost',
            name='content_type',
            field=models.CharField(blank=True, default='text', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='media/subcategory/thumbnail'),
        ),
    ]
