# Generated by Django 4.1.5 on 2023-02-07 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_profile_description_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='category/thumbnail'),
        ),
        migrations.AlterField(
            model_name='contenttopost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post/image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='post/thumbnail'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='user/picture'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='subcategory/thumbnail'),
        ),
    ]
