# Generated by Django 4.1.5 on 2023-02-07 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_code_profile_facebook_url_profile_instagram_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
