# Generated by Django 4.1.5 on 2023-02-09 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='thumbnail_200',
            field=models.ImageField(blank=True, null=True, upload_to='category/thumbnail_200'),
        ),
        migrations.AddField(
            model_name='category',
            name='thumbnail_500',
            field=models.ImageField(blank=True, null=True, upload_to='category/thumbnail_500'),
        ),
        migrations.AddField(
            model_name='post',
            name='thumbnail_200',
            field=models.ImageField(blank=True, null=True, upload_to='post/thumbnail_200'),
        ),
        migrations.AddField(
            model_name='post',
            name='thumbnail_500',
            field=models.ImageField(blank=True, null=True, upload_to='post/thumbnail_500'),
        ),
        migrations.AddField(
            model_name='profile',
            name='picture_thumbnail',
            field=models.ImageField(blank=True, help_text='upload max of 200X200', null=True, upload_to='user/picture_thumbnail'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='thumbnail_200',
            field=models.ImageField(blank=True, null=True, upload_to='subcategory/thumbnail_200'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='thumbnail_500',
            field=models.ImageField(blank=True, null=True, upload_to='subcategory/thumbnail_500'),
        ),
    ]
